// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.proto.xidian.edu.cn;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.proto.xidian.edu.cn.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
